language: node_js
node_js:
  - 0.12
  - 4
  - 5
  - 6
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
  - npm run build
